services:
  eureka-server:
    image: ghcr.io/danijel1989/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  user-service:
    image: ghcr.io/danijel1989/user-service:latest
    container_name: user-service
    networks:
      - microservices-network
    depends_on:
      - eureka-server

  product-service:
    image: ghcr.io/danijel1989/product-service:latest
    container_name: product-service
    networks:
      - microservices-network
    depends_on:
      - eureka-server

  api-gateway:
    image: ghcr.io/danijel1989/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
      - user-service
      - product-service

networks:
  microservices-network:
    external: true