server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**, /auth/**

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product-service/**
          filters:
            - AuthenticationFilter
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
