logging.level.com.microservices.user_service=DEBUG
logging.level.org.springframework.web=DEBUG

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/microservices
spring.datasource.username=postgres
spring.datasource.password=PostgresDev2026!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.jpa.hibernate.ddl-auto=update

product-service.name=PRODUCT-SERVICE

jwt.secret=${JWT_SECRET}

